export const codePenalLists = [
  {
    label: "Atteinte à la pudeur",
    categorie: "Contravention",
    amount: 800,
    peine: "00:00",
  },
  {
    label: "Conduite dangereuse mineur",
    categorie: "Contravention",
    amount: 1000,
    peine: "00:00",
  },
  {
    label: "Conduite dangereuse majeur",
    categorie: "Contravention",
    amount: 1800,
    peine: "00:00",
  },
  {
    label: "Conduite en contre-sens",
    categorie: "Contravention",
    amount: 750,
    peine: "00:00",
  },
  {
    label: "Conduite sans port de casque",
    categorie: "Contravention",
    amount: 750,
    peine: "00:00",
  },
  {
    label: "Dissimulation du visage",
    categorie: "Contravention",
    amount: 500,
    peine: "00:00",
  },
  {
    label: "Excès de vitesse 1-10km/h",
    categorie: "Contravention",
    amount: 500,
    peine: "00:00",
  },
  {
    label: "Excès de vitesse 11-20 km/h",
    categorie: "Contravention",
    amount: 1000,
    peine: "00:00",
  },
  {
    label: "Excès de vitesse 21-30 km/h",
    categorie: "Contravention",
    amount: 1500,
    peine: "00:00",
  },
  {
    label: "Excès de vitesse 31-50 km/h",
    categorie: "Contravention",
    amount: 2000,
    peine: "00:00",
  },
  {
    label: "Excès de vitesse 51+ km/h",
    categorie: "Contravention",
    amount: 3000,
    peine: "00:00",
  },
  {
    label: "Ivresse sur la voie publique",
    categorie: "Contravention",
    amount: 500,
    peine: "00:15",
  },
  {
    label: "Non présentation des papiers (ID, Permis)",
    categorie: "Contravention",
    amount: 500,
    peine: "00:00",
  },
  {
    label: "Non respect véhicule prioritaire",
    categorie: "Contravention",
    amount: 1500,
    peine: "00:00",
  },
  {
    label: "Nuisance sonore",
    categorie: "Contravention",
    amount: 700,
    peine: "00:10",
  },
  {
    label: "Possession du Kevlar sans PPA PRO",
    categorie: "Contravention",
    amount: 500,
    peine: "00:00",
  },
  {
    label: "Présence piétonne sur une autoroute",
    categorie: "Contravention",
    amount: 1000,
    peine: "00:00",
  },
  {
    label: "Rappel à la loi GRAVE",
    categorie: "Contravention",
    amount: 800,
    peine: "00:00",
  },
  {
    label: "Stationnement gênant",
    categorie: "Contravention",
    amount: 200,
    peine: "00:00",
  },
  {
    label: "Stationnement interdit",
    categorie: "Contravention",
    amount: 300,
    peine: "00:00",
  },
  {
    label: "Véhicule dégradé",
    categorie: "Contravention",
    amount: 800,
    peine: "00:00",
  },
  {
    label: "Véhicule non réglementaire",
    categorie: "Contravention",
    amount: 800,
    peine: "00:00",
  },
  {
    label: "Violation de propriété privée",
    categorie: "Contravention",
    amount: 1500,
    peine: "00:00",
  },
  {
    label: "Agression sur agent (employé d'état ou police)",
    categorie: "Délit mineur",
    amount: 3000,
    peine: "00:15",
  },
  {
    label: "Agression sur citoyen / Maltraitance animale",
    categorie: "Délit mineur",
    amount: 2000,
    peine: "00:10",
  },
  {
    label: "Appel abusif / Spam bipeur",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:00",
  },
  {
    label: "Braquage à main armée sur citoyens",
    categorie: "Délit mineur",
    amount: 2500,
    peine: "00:10",
  },
  {
    label: "Braquage à main armée de supérette",
    categorie: "Délit mineur",
    amount: 1500,
    peine: "00:10",
  },
  {
    label: "Cambriolage",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:10",
  },
  {
    label: "Cambriolage: Recel d'objet volé",
    categorie: "Délit mineur",
    amount: 20,
    peine: "00:05",
  },
  {
    label: "Conduite en état d'ivresse",
    categorie: "Délit mineur",
    amount: 2500,
    peine: "00:10",
  },
  {
    label: "Conduite sans permis",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:15",
  },
  {
    label: "Conduite sous interdiction de permis",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:10",
  },
  {
    label: "Course de rue illégale",
    categorie: "Délit mineur",
    amount: 800,
    peine: "00:10",
  },
  {
    label: "Dégradation de biens public",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:10",
  },
  {
    label: "Dégradation de biens privé",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:10",
  },
  {
    label: "Dégradation de matériels public (Ex: Véh LSPD)",
    categorie: "Délit mineur",
    amount: 800,
    peine: "00:10",
  },
  {
    label: "Délit de fuite",
    categorie: "Délit mineur",
    amount: 800,
    peine: "00:07",
  },
  {
    label: "Émeute",
    categorie: "Délit mineur",
    amount: 750,
    peine: "00:15",
  },
  {
    label: "Exhibition d’armes",
    categorie: "Délit mineur",
    amount: 200,
    peine: "00:00",
  },
  {
    label: "Franchissement d'un périmètre de sécurité",
    categorie: "Délit mineur",
    amount: 750,
    peine: "00:10",
  },
  {
    label: "Graffiti / Tag illégal",
    categorie: "Délit mineur",
    amount: 400,
    peine: "00:00",
  },
  {
    label: "Harcelement",
    categorie: "Délit mineur",
    amount: 750,
    peine: "00:10",
  },
  {
    label: "Manifestation",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:10",
  },
  {
    label: "Menaces de mort ET/OU Menaces grave",
    categorie: "Délit mineur",
    amount: 1500,
    peine: "00:00",
  },
  {
    label: "Mise en danger de la vie d’autrui",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:00",
  },
  {
    label: "Non assistance à personne en danger",
    categorie: "Délit mineur",
    amount: 200,
    peine: "00:00",
  },
  {
    label: "Non présentation à une convocation de police",
    categorie: "Délit mineur",
    amount: 750,
    peine: "00:00",
  },
  {
    label: "Non recensement",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:00",
  },
  {
    label: "Non respect du contrôle judiciaire",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:10",
  },
  {
    label: "Possession de Crack",
    categorie: "Délit mineur",
    amount: 130,
    peine: "00:07",
  },
  {
    label: "Possession de cannabis",
    categorie: "Délit mineur",
    amount: 140,
    peine: "00:15",
  },
  {
    label: "Possession de cocaïne",
    categorie: "Délit mineur",
    amount: 190,
    peine: "00:12",
  },
  {
    label: "Possession de methamphétamine",
    categorie: "Délit mineur",
    amount: 210,
    peine: "00:18",
  },
  {
    label: "Possession d'arme blanche",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:10",
  },
  {
    label: "Possession d’arme illégale légère sans PPA",
    categorie: "Délit mineur",
    amount: 4000,
    peine: "00:10",
  },
  {
    label: "Possession d’arme illégale légère",
    categorie: "Délit mineur",
    amount: 5000,
    peine: "00:10",
  },
  {
    label: "Refus d’obtempérer",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:06",
  },
  {
    label: "Survol de zone interdite",
    categorie: "Délit mineur",
    amount: 1000,
    peine: "00:10",
  },
  {
    label: "Vente de drogue",
    categorie: "Délit mineur",
    amount: 900,
    peine: "00:10",
  },
  {
    label: "Trouble à l’ordre public",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:10",
  },
  {
    label: "Vol à l'arraché",
    categorie: "Délit mineur",
    amount: 500,
    peine: "00:00",
  },
  {
    label: "Vol de véhicule Gouv/LSPD/EMS",
    categorie: "Délit mineur",
    amount: 5000,
    peine: "00:20",
  },
  {
    label: "Vol de véhicule d'entreprise",
    categorie: "Délit mineur",
    amount: 1500,
    peine: "00:10",
  },
  {
    label: "Vol de véhicule",
    categorie: "Délit mineur",
    amount: 800,
    peine: "00:05",
  },
  {
    label: "Entrave à une opération/enquête/justice",
    categorie: "Délit mineur",
    amount: 2500,
    peine: "00:15",
  },
  {
    label: "Possession de Grain (+20 graines)",
    categorie: "Délit mineur",
    amount: 2500,
    peine: "00:10",
  },
  {
    label: "Braquage de Bijouterie",
    categorie: "Délit majeur",
    amount: 7000,
    peine: "00:20",
  },
  {
    label: "Braquage de Convoi d'arme",
    categorie: "Délit majeur",
    amount: 4000,
    peine: "00:20",
  },
  {
    label: "Braquage de Fleeca",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:20",
  },
  {
    label: "Braquage de Train",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:20",
  },
  {
    label: "Braquage d'entreprise",
    categorie: "Délit majeur",
    amount: 3500,
    peine: "00:30",
  },
  {
    label: "Braquage du Musé",
    categorie: "Délit majeur",
    amount: 35000,
    peine: "00:30",
  },
  {
    label: "Braquage du Human Labs",
    categorie: "Délit majeur",
    amount: 3500,
    peine: "00:30",
  },
  {
    label: "Braquage du Union Depository",
    categorie: "Délit majeur",
    amount: 15000,
    peine: "00:30",
  },
  {
    label: "Détournement de fonds",
    categorie: "Délit majeur",
    amount: 25000,
    peine: "00:30",
  },
  {
    label: "Faux témoignage / Fausse accusation",
    categorie: "Délit majeur",
    amount: 15000,
    peine: "00:15",
  },
  {
    label: "Entreposage d'armes illégales (≥ 3)",
    categorie: "Délit majeur",
    amount: 4000,
    peine: "00:30",
  },
  {
    label: "Extorsion / Escroquerie / Racket",
    categorie: "Délit majeur",
    amount: 1500,
    peine: "00:10",
  },
  {
    label: "Multiples amendes impayées",
    categorie: "Délit majeur",
    amount: 3,
    peine: "00:30",
  },
  {
    label: "Possession d’argent liquide > 4K sans justificatif",
    categorie: "Délit majeur",
    amount: 0,
    peine: "00:10",
  },
  {
    label: "Possession d’arme illégale lourde (si arme de guerre = jugement)",
    categorie: "Délit majeur",
    amount: 6000,
    peine: "00:30",
  },
  {
    label: "Prise d'otage sur civil",
    categorie: "Délit majeur",
    amount: 3500,
    peine: "00:05",
  },
  {
    label: "Prise d'otage sur agent de l'état",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:30",
  },
  {
    label: "Trafic de drogue dure (x50 mini) = JUGEMENT",
    categorie: "Délit majeur",
    amount: 7000,
    peine: "00:30",
  },
  {
    label: "Tentative de meurtre sur civil",
    categorie: "Délit majeur",
    amount: 1000,
    peine: "00:30",
  },
  {
    label: "Usage de faux",
    categorie: "Délit majeur",
    amount: 3000,
    peine: "00:20",
  },
  {
    label: "Usurpation d'identité / fonction",
    categorie: "Délit majeur",
    amount: 3000,
    peine: "00:15",
  },
  {
    label: "Participation à une fusillade",
    categorie: "Délit majeur",
    amount: 7000,
    peine: "00:30",
  },
  {
    label: "Violation du secret pro / Droit de réserve",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:30",
  },
  {
    label: "Violation des lois de l'immigration",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:00",
  },
  {
    label: "Non présentiation d'un Visa/Passeport",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:00",
  },
  {
    label: "Outrage à magistrat",
    categorie: "Délit majeur",
    amount: 5000,
    peine: "00:00",
  },
  {
    label: "Parjure",
    categorie: "Délit majeur",
    amount: 10000,
    peine: "00:00",
  },
  {
    label: "Agression Sexuelle (viol, débordement HRP)",
    categorie: "Crime",
    amount: 0,
    peine: "168:00",
  },
  {
    label: "Braquage de la Pacifique Banque",
    categorie: "Crime",
    amount: 50000,
    peine: "24:00",
  },
  {
    label: "Trafic d'arme",
    categorie: "Crime",
    amount: 10000,
    peine: "00:45",
  },
  {
    label: "Braquage d'un Convoi pénitencier",
    categorie: "Crime",
    amount: 10000,
    peine: "12:00",
  },
  {
    label: "Attaque Gouvernementale",
    categorie: "Crime",
    amount: 150000,
    peine: "120:00",
  },
  {
    label: "Attaque Poste de Police",
    categorie: "Crime",
    amount: 120000,
    peine: "120:00",
  },
  {
    label: "Attentat",
    categorie: "Crime",
    amount: 400000,
    peine: "120:00",
  },
  {
    label: "Assassinat (meurtre prémédité)",
    categorie: "Crime",
    amount: 100000,
    peine: "168:00",
  },
  {
    label: "Association de malfaiteurs",
    categorie: "Crime",
    amount: 5000,
    peine: "12:00",
  },
  {
    label: "Blanchiment",
    categorie: "Crime",
    amount: 10,
    peine: "12:00",
  },
  {
    label: "Cavale",
    categorie: "Crime",
    amount: 50000,
    peine: "12:00",
  },
  {
    label: "Corruption",
    categorie: "Crime",
    amount: 30000,
    peine: "24:00",
  },
  {
    label: "Destruction / dissimulation de preuve",
    categorie: "Crime",
    amount: 45000,
    peine: "08:00",
  },
  {
    label: "Évasion / Organisation d’évasion",
    categorie: "Crime",
    amount: 10000,
    peine: "24:00",
  },
  {
    label: "Kidnapping / Séquestration",
    categorie: "Crime",
    amount: 6000,
    peine: "01:00",
  },
  {
    label: "Terrorisme",
    categorie: "Crime",
    amount: 300000,
    peine: "120:00",
  },
  {
    label: "Trafic et/ou Vol d'organe",
    categorie: "Crime",
    amount: 5000,
    peine: "12:00",
  },
  {
    label: "Trahison",
    categorie: "Crime",
    amount: 25000,
    peine: "24:00",
  },
  {
    label: "Tentative de meurte sur agent de l'état",
    categorie: "Crime",
    amount: 20000,
    peine: "00:35",
  },
  {
    label: "Tentative de meurte sur haut magistrat",
    categorie: "Crime",
    amount: 40000,
    peine: "12:00",
  },
  {
    label: "Possession d'arme illégale lourde (arme de guerre)",
    categorie: "Crime",
    amount: 8000,
    peine: "00:30",
  },
  {
    label: "Fraude fiscale",
    categorie: "Crime",
    amount: 11250,
    peine: "00:20",
  },
];
