export const access = [
  {
    page: "Accueil",
    path: "/",
    isCanAdd: false,
    isCanUpdate: false,
    isCanDelete: false,
  },
  {
    page: "MDT",
    childrens: "Encodage/Civils",
    path: "/mdt/encodage/civils",
    isCanAdd: false,
    isCanUpdate: false,
    isCanDelete: false,
  },
  {
    page: "MDT",
    childrens: "Encodages/Armes",
    path: "/mdt/encodage/armes",
    isCanAdd: true,
    isCanUpdate: false,
    isCanDelete: false,
  },
  {
    page: "MDT",
    childrens: "Panic Bouton",
    path: "/mdt/panic-bouton",
    isCanAdd: true,
    isCanUpdate: false,
    isCanDelete: false,
  },
  {
    page: "MDT",
    childrens: "MDT/Encodage/Véhicules/Voitures",
    path: "/mdt/encodage/vehicules",
    isCanAdd: true,
    isCanUpdate: false,
    isCanDelete: false,
  },
  {
    page: "Services",
    childrens: "Feuilles d'heures",
    path: "/services/feuille-d-heures",
    isCanAdd: true,
    isCanUpdate: false,
    isCanDelete: false,
  },
];
